# list_append_prefixed( LIST_VAR PREFIX prefix item1 item2 ... )
function( list_append_prefixed LIST )
  cmake_parse_arguments( ARG "" PREFIX "" ${ARGN} )
  set( RESULT ${${LIST}} )
  foreach( ITEM IN LISTS ARG_UNPARSED_ARGUMENTS )
    list( APPEND RESULT "${ARG_PREFIX}${ITEM}" )
  endforeach( )
  set( ${LIST} ${RESULT} PARENT_SCOPE )
endfunction( )
